/* ************************************************************************** */
/*                                                                            */
/*                                                        ::::::::            */
/*   main.c                                             :+:    :+:            */
/*                                                     +:+                    */
/*   By: mraasvel <mraasvel@student.codam.nl>         +#+                     */
/*                                                   +#+                      */
/*   Created: 2020/12/21 16:53:44 by mraasvel      #+#    #+#                 */
/*   Updated: 2020/12/21 19:46:54 by mraasvel      ########   odam.nl         */
/*                                                                            */
/* ************************************************************************** */

#include "ascii.h"

const char *files[] = {
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-1.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-2.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-3.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-4.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-5.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-6.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-7.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-8.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-9.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-10.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-11.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-12.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-13.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-14.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-15.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-16.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-17.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-18.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-19.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-20.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-21.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-22.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-23.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-24.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-25.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-26.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-27.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-28.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-29.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-30.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-31.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-32.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-33.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-34.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-35.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-36.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-37.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-38.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-39.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-40.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-41.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-42.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-43.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-44.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-45.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-46.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-47.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-48.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-49.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-50.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-51.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-52.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-53.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-54.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-55.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-56.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-57.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-58.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-59.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-60.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-61.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-62.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-63.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-64.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-65.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-66.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-67.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-68.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-69.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-70.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-71.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-72.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-73.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-74.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-75.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-76.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-77.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-78.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-79.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-80.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-81.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-82.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-83.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-84.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-85.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-86.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-87.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-88.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-89.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-90.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-91.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-92.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-93.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-94.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-95.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-96.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-97.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-98.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-99.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-100.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-101.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-102.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-103.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-104.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-105.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-106.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-107.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-108.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-109.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-110.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-111.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-112.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-113.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-114.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-115.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-116.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-117.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-118.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-119.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-120.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-121.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-122.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-123.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-124.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-125.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-126.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-127.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-128.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-129.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-130.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-131.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-132.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-133.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-134.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-135.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-136.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-137.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-138.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-139.txt",
	"/home/mraasvel/work/mraasvel-collective/art/ascii-art-140.txt",
	NULL
};

int	main(void)
{
	display_frames(files);
	return (0);
}
